import { Product } from './store';

export const categories = [
  {
    id: 'wires-cables',
    name: 'Wires & Cables',
    slug: 'wires-cables',
    icon: 'Cable',
    image: 'https://images.unsplash.com/photo-1605110783340-9aa2c6d5d5b3?w=400&h=400&fit=crop',
    subCategories: ['Copper Wires', 'Aluminum Wires', 'Coaxial Cables', 'LAN Cables', 'HDMI Cables'],
  },
  {
    id: 'switches-sockets',
    name: 'Switches & Sockets',
    slug: 'switches-sockets',
    icon: 'ToggleRight',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop',
    subCategories: ['Modular Switches', 'Socket Outlets', 'Fan Regulators', 'Dimmers', 'USB Chargers'],
  },
  {
    id: 'lights-lighting',
    name: 'Lights & Lighting',
    slug: 'lights-lighting',
    icon: 'Lightbulb',
    image: 'https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=400&h=400&fit=crop',
    subCategories: ['LED Bulbs', 'Tube Lights', 'CFL Lights', 'Downlights', 'Spotlights', 'Chandeliers'],
  },
  {
    id: 'fans',
    name: 'Fans',
    slug: 'fans',
    icon: 'Wind',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400&h=400&fit=crop',
    subCategories: ['Ceiling Fans', 'Exhaust Fans', 'Table Fans', 'Pedestal Fans', 'Wall Fans'],
  },
  {
    id: 'mcbs-rccbs',
    name: 'MCBs & RCCBs',
    slug: 'mcbs-rccbs',
    icon: 'Zap',
    image: 'https://images.unsplash.com/photo-1555664424-778a1e5e1b48?w=400&h=400&fit=crop',
    subCategories: ['Single Pole MCB', 'Double Pole MCB', 'Triple Pole MCB', 'RCCB', 'MCB Box'],
  },
  {
    id: 'electrical-accessories',
    name: 'Electrical Accessories',
    slug: 'electrical-accessories',
    icon: 'Wrench',
    image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=400&h=400&fit=crop',
    subCategories: ['Junction Boxes', 'Conduits', 'PVC Pipes', 'Cable Ties', 'Tape'],
  },
  {
    id: 'industrial-motors',
    name: 'Industrial Motors',
    slug: 'industrial-motors',
    icon: 'Settings',
    image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=400&h=400&fit=crop',
    subCategories: ['Single Phase Motor', 'Three Phase Motor', 'Submersible Motor', 'Servo Motor'],
  },
  {
    id: 'solar-products',
    name: 'Solar Products',
    slug: 'solar-products',
    icon: 'Sun',
    image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=400&h=400&fit=crop',
    subCategories: ['Solar Panels', 'Solar Inverter', 'Solar Battery', 'Solar Lights'],
  },
];

export const brands = [
  'Havells',
  'Luminous',
  'Syska',
  'Philips',
  'Bajaj',
  'Anchor',
  'Legrand',
  'Schneider',
  'Polycab',
  'Finolex',
];

export const products: Product[] = [
  {
    id: 'prod-001',
    name: 'Havells Life Long LED Bulb 12W',
    slug: 'havells-life-long-led-bulb-12w',
    description: 'High-efficiency LED bulb with 12W power consumption. Provides bright illumination while saving energy. Long lifespan of up to 25,000 hours. Perfect for home and office use.',
    price: 99,
    originalPrice: 199,
    images: [
      'https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1605110783340-9aa2c6d5d5b3?w=800&h=800&fit=crop',
    ],
    category: 'lights-lighting',
    brand: 'Havells',
    stock: 150,
    rating: 4.5,
    reviews: 234,
    features: ['12W Power', '1500 Lumens', '25,000 Hours Life', 'Cool Day Light'],
    tags: ['led bulb', '12w', 'havells', 'energy saving'],
    isFeatured: true,
    isTrending: true,
    isNew: false,
    isSale: true,
    saleEnds: '2026-04-30',
  },
  {
    id: 'prod-002',
    name: 'Polycab Gold FLR Cable 1.5 sq mm',
    slug: 'polycab-gold-flr-cable-1-5-sq-mm',
    description: 'High-quality copper flexible wire for internal wiring. ISI marked for safety. Excellent heat resistance and durability. Suitable for domestic and commercial installations.',
    price: 285,
    originalPrice: 350,
    images: [
      'https://images.unsplash.com/photo-1605110783340-9aa2c6d5d5b3?w=800&h=800&fit=crop',
    ],
    category: 'wires-cables',
    brand: 'Polycab',
    stock: 500,
    rating: 4.7,
    reviews: 456,
    features: ['1.5 sq mm', '100m Roll', 'Copper Conductor', 'ISI Marked'],
    tags: ['wire', 'cable', 'polycab', '1.5 sq mm'],
    isFeatured: true,
    isTrending: false,
    isNew: false,
    isSale: true,
  },
  {
    id: 'prod-003',
    name: 'Havells 1200mm Ceiling Fan',
    slug: 'havells-1200mm-ceiling-fan',
    description: 'Premium ceiling fan with powerful air delivery. Sleek design with anti-dust technology. Energy efficient and silent operation. Comes with 2-year warranty.',
    price: 2199,
    originalPrice: 2899,
    images: [
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&h=800&fit=crop',
    ],
    category: 'fans',
    brand: 'Havells',
    stock: 75,
    rating: 4.6,
    reviews: 189,
    features: ['1200mm Sweep', '72W Power', 'Silent Operation', '2 Year Warranty'],
    tags: ['ceiling fan', '1200mm', 'havells', 'fan'],
    isFeatured: true,
    isTrending: true,
    isNew: false,
    isSale: true,
  },
  {
    id: 'prod-004',
    name: 'Anchor Roma 6A Switch Socket',
    slug: 'anchor-roma-6a-switch-socket',
    description: 'Premium quality modular switch socket from Anchor. Modern design with smooth finish. Fire-retardant material for safety. Easy to install.',
    price: 45,
    originalPrice: 65,
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=800&fit=crop',
    ],
    category: 'switches-sockets',
    brand: 'Anchor',
    stock: 1000,
    rating: 4.4,
    reviews: 567,
    features: ['6A Rating', 'Modular Design', 'Fire Retardant', 'White Finish'],
    tags: ['switch', 'socket', 'anchor', '6a'],
    isFeatured: false,
    isTrending: false,
    isNew: false,
    isSale: true,
  },
  {
    id: 'prod-005',
    name: 'Syska LED Tube Light 20W',
    slug: 'syska-led-tube-light-20w',
    description: 'Energy-efficient LED tube light with 20W power. Provides uniform illumination. Long-lasting with 50,000 hours lifespan. Instant start functionality.',
    price: 249,
    originalPrice: 399,
    images: [
      'https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=800&h=800&fit=crop',
    ],
    category: 'lights-lighting',
    brand: 'Syska',
    stock: 200,
    rating: 4.3,
    reviews: 321,
    features: ['20W Power', '2000 Lumens', '50,000 Hours', 'Instant Start'],
    tags: ['led tube', '20w', 'syska', 'tube light'],
    isFeatured: false,
    isTrending: true,
    isNew: false,
    isSale: true,
  },
  {
    id: 'prod-006',
    name: 'Luminous 150Ah Tall Tubular Battery',
    slug: 'luminous-150ah-tall-tubular-battery',
    description: 'High-capacity tubular battery for inverters. Long backup with fast charging. Low maintenance with advanced water management. 5-year warranty.',
    price: 12500,
    originalPrice: 15000,
    images: [
      'https://images.unsplash.com/photo-1619641805634-98e5c0836f1f?w=800&h=800&fit=crop',
    ],
    category: 'solar-products',
    brand: 'Luminous',
    stock: 25,
    rating: 4.8,
    reviews: 89,
    features: ['150Ah Capacity', 'Tall Tubular', '5 Year Warranty', 'Fast Charging'],
    tags: ['battery', 'inverter', '150ah', 'luminous'],
    isFeatured: true,
    isTrending: false,
    isNew: true,
    isSale: true,
  },
  {
    id: 'prod-007',
    name: 'Schneider 32A Double Pole MCB',
    slug: 'schneider-32a-double-pole-mcb',
    description: 'High-quality miniature circuit breaker from Schneider. Provides protection against overload and short circuit. DIN rail mountable. Quick response.',
    price: 450,
    originalPrice: 550,
    images: [
      'https://images.unsplash.com/photo-1555664424-778a1e5e1b48?w=800&h=800&fit=crop',
    ],
    category: 'mcbs-rccbs',
    brand: 'Schneider',
    stock: 150,
    rating: 4.6,
    reviews: 145,
    features: ['32A Rating', 'Double Pole', '10kA Breaking Capacity', 'DIN Rail Mount'],
    tags: ['mcb', '32a', 'schneider', 'circuit breaker'],
    isFeatured: false,
    isTrending: true,
    isNew: false,
    isSale: false,
  },
  {
    id: 'prod-008',
    name: 'Legrand 3 Module Indicator',
    slug: 'legrand-3-module-indicator',
    description: 'Premium modular indicator light from Legrand. Modern design with LED technology. Low power consumption. Suitable for residential and commercial.',
    price: 180,
    originalPrice: 220,
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=800&fit=crop',
    ],
    category: 'switches-sockets',
    brand: 'Legrand',
    stock: 300,
    rating: 4.5,
    reviews: 78,
    features: ['3 Module', 'LED Technology', 'Low Power', 'Premium Finish'],
    tags: ['indicator', 'led', 'legrand', 'modular'],
    isFeatured: false,
    isTrending: false,
    isNew: true,
    isSale: false,
  },
  {
    id: 'prod-009',
    name: 'Finolex 25mm PVC Conduit Pipe',
    slug: 'finolex-25mm-pvc-conduit-pipe',
    description: 'High-quality PVC conduit for electrical wiring. ISI marked. Fire-retardant. Easy to install with smooth inner surface for wire pulling.',
    price: 320,
    originalPrice: 400,
    images: [
      'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&h=800&fit=crop',
    ],
    category: 'electrical-accessories',
    brand: 'Finolex',
    stock: 800,
    rating: 4.4,
    reviews: 234,
    features: ['25mm Diameter', '3m Length', 'ISI Marked', 'Fire Retardant'],
    tags: ['conduit', 'pvc', 'finolex', 'pipe'],
    isFeatured: false,
    isTrending: false,
    isNew: false,
    isSale: true,
  },
  {
    id: 'prod-010',
    name: 'Bajaj LED Desk Lamp',
    slug: 'bajaj-led-desk-lamp',
    description: 'Modern LED desk lamp with touch control. Adjustable brightness and color temperature. USB charging port. Eye protection technology.',
    price: 899,
    originalPrice: 1299,
    images: [
      'https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=800&h=800&fit=crop',
    ],
    category: 'lights-lighting',
    brand: 'Bajaj',
    stock: 120,
    rating: 4.5,
    reviews: 167,
    features: ['Touch Control', 'USB Port', 'Adjustable Brightness', 'Eye Protection'],
    tags: ['desk lamp', 'led', 'bajaj', 'table lamp'],
    isFeatured: true,
    isTrending: true,
    isNew: true,
    isSale: true,
  },
  {
    id: 'prod-011',
    name: 'Havells 4 Way Modular Board',
    slug: 'havells-4-way-modular-board',
    description: 'Premium modular switch board from Havells. Fire-retardant material. Sleek design with smooth finish. Easy to install and maintain.',
    price: 150,
    originalPrice: 200,
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=800&fit=crop',
    ],
    category: 'switches-sockets',
    brand: 'Havells',
    stock: 400,
    rating: 4.3,
    reviews: 189,
    features: ['4 Way', 'Modular Design', 'Fire Retardant', 'Premium Finish'],
    tags: ['board', 'modular', 'havells', 'switch board'],
    isFeatured: false,
    isTrending: false,
    isNew: false,
    isSale: true,
  },
  {
    id: 'prod-012',
    name: 'Syska 100W Solar Panel',
    slug: 'syska-100w-solar-panel',
    description: 'High-efficiency monocrystalline solar panel. 100W power output. Weather-resistant design. 25-year performance warranty. Perfect for home solar systems.',
    price: 8500,
    originalPrice: 10500,
    images: [
      'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&h=800&fit=crop',
    ],
    category: 'solar-products',
    brand: 'Syska',
    stock: 30,
    rating: 4.7,
    reviews: 56,
    features: ['100W Power', 'Monocrystalline', '25 Year Warranty', 'Weather Resistant'],
    tags: ['solar panel', '100w', 'syska', 'solar'],
    isFeatured: true,
    isTrending: false,
    isNew: true,
    isSale: true,
  },
];

export const banners = [
  {
    id: 'banner-001',
    title: 'Summer Sale',
    subtitle: 'Up to 50% Off',
    description: 'Flat discounts on all electrical products',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=400&fit=crop',
    cta: 'Shop Now',
    link: '/products?category=lights-lighting',
    backgroundColor: '#ed7609',
  },
  {
    id: 'banner-002',
    title: 'New Arrivals',
    subtitle: 'Latest Products',
    description: 'Check out our newest electrical solutions',
    image: 'https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=1200&h=400&fit=crop',
    cta: 'Explore',
    link: '/products?new=true',
    backgroundColor: '#22c55e',
  },
  {
    id: 'banner-003',
    title: 'Free Installation',
    subtitle: 'On Orders Above ₹2000',
    description: 'Professional installation by certified technicians',
    image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=1200&h=400&fit=crop',
    cta: 'Know More',
    link: '/services/installation',
    backgroundColor: '#3b82f6',
  },
];

export const testimonials = [
  {
    id: 'test-001',
    name: 'Rajesh Kumar',
    location: 'Delhi',
    rating: 5,
    comment: 'Excellent product quality and fast delivery. The team was very helpful in choosing the right electrical items for my new home.',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face',
  },
  {
    id: 'test-002',
    name: 'Priya Sharma',
    location: 'Mumbai',
    rating: 5,
    comment: 'Best prices in the market for electrical products. Ordered MCBs and wires for my office renovation. Very satisfied with the service.',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face',
  },
  {
    id: 'test-003',
    name: 'Amit Patel',
    location: 'Ahmedabad',
    rating: 4,
    comment: 'Great shopping experience. Products are authentic and the delivery was on time. Will definitely order again.',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face',
  },
];

export const shopInfo = {
  name: 'Dinesh Electrical',
  tagline: 'Your Trusted Electrical Partner',
  description: 'Dinesh Electrical is a leading provider of quality electrical products in India. We offer a wide range of wires, switches, lights, fans, and more at competitive prices.',
  address: 'Shop No. 12, Main Market, Near Bus Stand, City Center',
  city: 'Your City',
  state: 'Your State',
  pincode: '123456',
  phone: '+91 98765 43210',
  whatsapp: '+91 98765 43210',
  email: 'contact@dineshelectricals.com',
  workingHours: 'Mon-Sat: 9:00 AM - 8:00 PM',
  googleMapUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3502.0123456789!2d77.123456!3d28.654321!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMjjCsDM5JzE2LjYiTiA3N8KwMDcnMjMuNCJF!5e0!3m2!1sen!2sin!4v1234567890',
  socialLinks: {
    facebook: 'https://facebook.com/dineshelectricals',
    instagram: 'https://instagram.com/dineshelectricals',
    twitter: 'https://twitter.com/dineshelectricals',
    youtube: 'https://youtube.com/dineshelectricals',
  },
};